### ISSUE TITLE
DM- when delete last message preview date doesnt change

### ISSUE THREAD

**Issue by NoamQA** [daostack/common-backend#1956]
date of the preview should return to the last message date
works on other channels
but not for DM
related to [#1916](https://github.com/daostack/common-backend/issues/1916)

![Image](https://user-images.githubusercontent.com/129174316/250469561-ce0a6c93-6724-437a-b6a1-c9562ea20f3c.png)

**Comment by elatif2020** [comment]
@roienatan @danielr18 
can you figure out whether it should be fixed in the FE or BE ?

**Comment by elatif2020** [comment]
@andreymikhadyuk can you please check this?

**Comment by andreymikhadyuk** [comment]
@elatif2020 It is BE, because the date is incorrect even after reloading the page.

**Comment by ariel-dao** [comment]
@andreymikhadyuk Where are you pulling the data from? The chat channel was updated correctly, inbox item `updatedAt` will now be updated as well. Deployed to dev

**Comment by NoamQA** [comment]
@ariel-dao 
:x: date still doesnt change in dev for last message date...
![image](https://github.com/daostack/common-backend/assets/129174316/c25aa1e9-7a75-40dc-acd6-ffa0c0d71330)

**Comment by andreymikhadyuk** [comment]
> @andreymikhadyuk Where are you pulling the data from? The chat channel was updated correctly, inbox item `updatedAt` will now be updated as well. Deployed to dev

We use `chatChannel.updatedAt`. It worked fine as I remember for new messages.

**Comment by ariel-dao** [comment]
Are we sure this is a backend issue? I can see the data being updated on db

**Comment by andreymikhadyuk** [comment]
@ariel-dao I will double-check.

**Comment by andreymikhadyuk** [comment]
@ariel-dao after deleting a chat channel message the `updatedAt` is updated to the date of actual deletion request, not to the date of the last message. which is logical. should we use `createdAt` of `lastMessage` to display last activity of chat channel?

**Comment by ariel-dao** [comment]
deployed to dev fix

**Comment by NoamQA** [comment]
:x: doesnt work on prod...
in dev its fine

![Image](https://github.com/daostack/common-backend/assets/129174316/75b15988-fa42-4de3-b483-9e3e254dc345)
